CREATE TABLE "Nguoi_dung" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "ten_dang_nhap" VARCHAR(255) NOT NULL,
  "mat_khau" VARCHAR(255) NOT NULL,	
  "gioi_tinh" CHAR(3) NOT NULL,
  "ho_va_ten" VARCHAR(255) NOT NULL,
  "avt_url" VARCHAR(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "Thuoc" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_thuoc" VARCHAR(255),
  "mo_ta" TEXT,
  "don_vi" VARCHAR(255),
  "quy_che" TEXT,
  "cach_dung" TEXT,
  "url" VARCHAR(255),
  "bi_xoa" BOOLEAN DEFAULT FALSE,
  "id_nguoi_dung" INTEGER,
  FOREIGN KEY ("id_nguoi_dung") REFERENCES "Nguoi_dung" ("id")
);

CREATE TABLE "Don_thuoc" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_nguoi_dung" INTEGER,
  "ngay_bat_dau" DATE,
  "ngay_ket_thuc" DATE,
  "trang_thai" varchar(50), --Đang chờ, Hoàn thành, Đã hủy
  "ten_don_thuoc" varchar(255),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("id_nguoi_dung") REFERENCES "Nguoi_dung" ("id")
);

CREATE TABLE "Don_chua_thuoc" (
  "thuoc" varchar(255),
  "id_don_thuoc" INTEGER,
  "tong_so" INTEGER,
  "buoi_uong" varchar(50), --[Sáng, Trưa, Chiều]
  "ghi_chu" varchar(255),
  PRIMARY KEY ("thuoc", "id_don_thuoc"),
  FOREIGN KEY ("id_don_thuoc") REFERENCES "Don_thuoc" ("id")
);

CREATE TABLE "Lan_uong" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "gio" TIME,
  "ngay" DATE,
  "don_thuoc" INTEGER,
  "thoi_diem_da_uong" TIMESTAMP,
  "buoi_uong" varchar(10), --Sáng, Trưa, Tối
  PRIMARY KEY ("id"),
  UNIQUE ("gio", "ngay", "don_thuoc"),
  FOREIGN KEY ("don_thuoc") REFERENCES "Don_thuoc" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "Thanh_phan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "thuoc_id" INTEGER NOT NULL,
  "ten_thanh_phan" VARCHAR(255) NOT NULL,
  "ham_luong" VARCHAR(100),
  FOREIGN KEY ("thuoc_id") REFERENCES "Thuoc"("id") ON DELETE CASCADE
);

CREATE TABLE "Thuoc_trong_mot_lan_uong" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_lan_uong" INTEGER,
  "thuoc" varchar(255),
  "so_luong" INTEGER,
  PRIMARY KEY ("id"),
  UNIQUE ("id_lan_uong", "thuoc"),
  FOREIGN KEY ("id_lan_uong") REFERENCES "Lan_uong" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "Token_thong_bao" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "token" VARCHAR(255),
  "id_nguoi_dung" INTEGER,
  UNIQUE ("token"),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("id_nguoi_dung") REFERENCES "Nguoi_dung" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
  )