// CREATE TABLE "ThanhPhan" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     "thuoc_id" INTEGER NOT NULL,
//     "ten_thanh_phan" VARCHAR(255) NOT NULL,
//     "ham_luong" VARCHAR(100),
//     FOREIGN KEY ("thuoc_id") REFERENCES "Thuoc"("id") ON DELETE CASCADE
//   );

const { DataTypes } = require("sequelize");

module.exports = (sequelize) => {
  return sequelize.define(
    "Ingredient",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      thuoc_id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: "Thuoc",
          key: "id",
        },
      },
      ten_thanh_phan: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      ham_luong: {
        type: DataTypes.STRING(100),
        allowNull: true,
      },
    },
    {
      tableName: "Thanh_phan",
      timestamps: false,
    }
  );
};
