const { DataTypes } = require("sequelize");
// CREATE TABLE "Thuoc_trong_mot_lan_uong" (
//   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//   "id_lan_uong" INTEGER,
//     "thuoc" varchar(255),
//   "so_luong" INTEGER,
//   PRIMARY KEY ("id"),
//     UNIQUE ("id_lan_uong", "thuoc"),
// FOREIGN KEY ("thuoc") REFERENCES "Don_chua_thuoc" ("thuoc") ON DELETE NO ACTION ON UPDATE NO ACTION,
// FOREIGN KEY ("id_lan_uong") REFERENCES "Lan_uong" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
// );
module.exports = (sequelize) => {
  return sequelize.define(
    "MedicineInSingleDose",
    {
      id: {
        // ID của thuốc trong một lần uống
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      id_lan_uong: {
        // ID của lần uống thuốc
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        references: {
          model: "Lan_uong",
          key: "id",
        },
      },
      thuoc: {
        // ID thuốc
        type: DataTypes.STRING(255),
        allowNull: false,
        primaryKey: true,
        references: {
          model: "Don_chua_thuoc",
          key: "thuoc",
        },
      },
      so_luong: {
        // Số lượng thuốc
        type: DataTypes.INTEGER,
        allowNull: true,
      },
    },
    {
      tableName: "Thuoc_trong_mot_lan_uong", // Tên bảng trong cơ sở dữ liệu
      timestamps: false, // Không sử dụng createdAt và updatedAt
      uniqueKeys: {
        // Đảm bảo rằng mỗi lần uống thuốc chỉ có một loại thuốc duy nhất
        uniqueKey: "unique_medicine_in_single_dose",
        fields: ["id_lan_uong", "thuoc"],
      },
    }
  );
};
