const { DataTypes } = require("sequelize");
// CREATE TABLE "Lan_uong" (
//   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//   "gio" TIME,
//   "ngay" DATE,
//   "don_thuoc" INTEGER,
//   "thoi_diem_da_uong" TIMESTAMP,
//   "buoi_uong" varchar(10), --Sáng, Trưa, Tối
//   PRIMARY KEY ("id"),
//   UNIQUE ("gio", "ngay", "don_thuoc"),
//   FOREIGN KEY ("don_thuoc") REFERENCES "Don_thuoc" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
// );
module.exports = (sequelize) => {
  return sequelize.define(
    "MedicationSchedule",
    {
      id: {
        // ID của lịch trình uống thuốc
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      gio: {
        // Giờ uống thuốc
        type: DataTypes.TIME,
        allowNull: false,
      },
      ngay: {
        // Ngày uống thuốc
        type: DataTypes.DATE,
        allowNull: false,
      },
      don_thuoc: {
        // Đơn thuốc, liên kết tới bảng Don_thuoc
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: "Don_thuoc",
          key: "id",
        },
      },
      thoi_diem_da_uong: {
        // Thời điểm đã uống thuốc
        type: DataTypes.DATE,
        allowNull: true,
      },
      buoi_uong: {
        type: DataTypes.STRING(10),
        allowNull: false,
      },
    },
    {
      tableName: "Lan_uong", // Tên bảng trong cơ sở dữ liệu
      timestamps: false, // Không sử dụng createdAt và updatedAt
      uniqueKeys: {
        // Đảm bảo UNIQUE trên khóa chính
        unique_lan_uong: {
          fields: ["gio", "ngay", "don_thuoc"],
        },
      },
    }
  );
};
