const { DataTypes } = require("sequelize");
// CREATE TABLE "Token_thong_bao" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "token" VARCHAR(255),
//     "thiet_bi" VARCHAR(255),
//     "id_nguoi_dung" INTEGER,
//     UNIQUE ("token", "thiet_bi"),
//     PRIMARY KEY ("id"),
//     FOREIGN KEY ("id_nguoi_dung") REFERENCES "Nguoi_dung" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
//     )
module.exports = (sequelize) => {
  return sequelize.define(
    "NotificationToken",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      token: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      id_nguoi_dung: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: "Nguoi_dung",
          key: "id",
        },
      },
    },
    {
      tableName: "Token_thong_bao",
      timestamps: false,
    }
  );
};
